version: '3'
services:
  auth-db:
    image: postgres:9.4
    container_name: auth-db
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./postgres-data:/var/lib/postgresql/dat
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres

  auth-api:
    env_file: .env
    container_name: auth-api
    build: .
    depends_on:
      - auth-db
    restart: on-failure
    ports:
      - "5000:5000"





