version: "3"
services:
  auth-db:
    image: postgres:9.4
    container_name: auth-db
    # ports:
    #   - "5432:5432"
    restart: on-failure
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/dat
    environment:
      POSTGRES_PASSWORD: password
      # POSTGRES_USER: admin
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_DATABASE: ${POSTGRES_DATABASE}

  auth-api:
    env_file: .env
    container_name: auth-api
    links:
      - auth-db
    build: .
    depends_on:
      - auth-db
    ports:
      - "3000:3000"
    restart: always
